# Generated by Django 6.0.7 on 2026-07-21 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plano', 'Plano (PDF/DWG)'), ('render', 'Render'), ('modelo_3d', 'Modelo 3D / USDZ (LiDAR)'), ('nube_puntos', 'Nube de puntos')], max_length=20)),
                ('archivo', models.FileField(upload_to='arquitectura/%Y/%m/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaDiseno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estatus', models.CharField(choices=[('boceto', 'Boceto'), ('revision', 'En revisión'), ('aprobado', 'Aprobado')], default='boceto', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
