# Generated by Django 6.0.7 on 2026-07-21 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquitectura', '0001_initial'),
        ('core', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestadiseno',
            name='arquitecto_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_diseno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propuestadiseno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_diseno', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='propuestadiseno',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_diseno', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='archivodiseno',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='arquitectura.propuestadiseno'),
        ),
    ]
