# Generated by Django 5.2.17 on 2026-08-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivodiseno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
