# Generated by Django 5.2.17 on 2026-08-19 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_empresa_options_alter_rol_options_and_more'),
        ('proyectos', '0002_alter_fase_id_participacionempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ventas_mes', 'Ventas del mes'), ('avance_fisico', 'Avance físico'), ('avance_proyectos', '% avance general'), ('proyectos_entregados', 'Proyectos a tiempo'), ('flujo_caja', 'Flujo de caja'), ('margen', 'Margen consolidado'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unidad', models.CharField(default='%', max_length=20)),
                ('area', models.CharField(choices=[('comercial', 'Comercial'), ('arquitectura', 'Arquitectura'), ('proyectos', 'Proyectos'), ('obra', 'Obra'), ('financiero', 'Financiero'), ('rrhh', 'RH'), ('produccion', 'Producción')], max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_referencia', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores', to='core.empresa')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores', to='proyectos.proyecto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador / KPI',
                'verbose_name_plural': 'Indicadores / KPIs',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['area', 'fecha_registro'], name='direccion_g_area_cda4de_idx'), models.Index(fields=['empresa', 'fecha_registro'], name='direccion_g_empresa_86fa85_idx')],
            },
        ),
    ]
