# Generated by Django 5.2.17 on 2026-08-19 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_options_alter_rol_options_and_more'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ParticipacionEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_presupuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0)),
                ('estatus_cancha', models.CharField(choices=[('no_iniciado', 'Por Iniciar'), ('en_cancha', 'Área Responsable Principal'), ('pari_passu', 'Ejecución Concurrente'), ('completado', 'Etapa Concluida'), ('detenido', 'En Pausa Estratégica')], db_index=True, default='no_iniciado', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones_proyecto', to='core.empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['empresa__nombre'],
                'unique_together': {('proyecto', 'empresa')},
            },
        ),
    ]
