# Generated by Django 6.0.7 on 2026-07-21 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vigencia', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='cotizaciones/')),
                ('aprobada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen', models.CharField(choices=[('referido', 'Referido'), ('web', 'Sitio web'), ('redes', 'Redes sociales'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('estatus', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_seguimiento', 'En seguimiento'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_firma', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='comercial.cotizacion')),
            ],
        ),
    ]
