# Generated by Django 6.0.7 on 2026-07-21 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='empresa',
            field=models.ForeignKey(help_text='Línea de negocio: Desarrollo, Arquitectura o Producción', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='lead',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='comercial.lead'),
        ),
    ]
