# Generated by Django 5.2.17 on 2026-08-19 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_initial'),
        ('core', '0002_alter_empresa_options_alter_rol_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='aprobada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estatus',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_seguimiento', 'En seguimiento'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], db_index=True, default='nuevo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['estatus', 'empresa'], name='comercial_l_estatus_68ad84_idx'),
        ),
    ]
