# Generated by Django 5.2.17 on 2026-08-20 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_alter_lead_options_alter_cotizacion_aprobada_and_more'),
        ('core', '0002_alter_empresa_options_alter_rol_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada Telefónica'), ('whatsapp', 'Mensaje de WhatsApp'), ('correo', 'Correo Electrónico'), ('reunion', 'Reunión / Visita Presencial'), ('sistema', 'Evento del Sistema')], default='llamada', max_length=20)),
                ('resultado_notas', models.TextField()),
                ('proximo_seguimiento', models.DateField(blank=True, null=True)),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Interacción con Cliente',
                'verbose_name_plural': 'Interacciones con Clientes',
                'ordering': ['-fecha_contacto'],
            },
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='comercial_l_estatus_68ad84_idx',
        ),
        migrations.AddField(
            model_name='interaccioncliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='interaccioncliente',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='comercial.lead'),
        ),
        migrations.AddField(
            model_name='interaccioncliente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones_comerciales', to=settings.AUTH_USER_MODEL),
        ),
    ]
