# Generated by Django 5.2.17 on 2026-08-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_interaccioncliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaccioncliente',
            options={'ordering': ['-fecha_contacto']},
        ),
        migrations.AddField(
            model_name='lead',
            name='entregables_esperados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_cotizacion_requerida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_entrega_requerida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_inamovible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_inicio_solicitado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='informacion_existente',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='liga_carpeta_adjuntos',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='monto_presupuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='lead',
            name='necesidad_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='observaciones_importantes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='presupuesto_indicado',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('pendiente', 'Aún no se ha preguntado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='siguiente_accion_area',
            field=models.CharField(default='Diseño / Arquitectura', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='siguiente_accion_concreta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='siguiente_accion_fecha_compromiso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sucursal_ubicacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='lead',
            name='tipos_proyecto',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estatus',
            field=models.CharField(choices=[('solicitud_inicial', 'Solicitud Inicial'), ('requiere_propuesta', 'Requiere Propuesta'), ('requiere_presupuesto', 'Requiere Presupuesto'), ('en_negociacion', 'En Negociación'), ('autorizado', 'Autorizado para Desarrollar'), ('ganado', 'Proyecto Vendido / Ganado'), ('perdido', 'Perdido')], db_index=True, default='solicitud_inicial', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origen',
            field=models.CharField(choices=[('referido', 'Referido'), ('web', 'Sitio Web'), ('redes', 'Redes Sociales'), ('otro', 'Otro')], default='web', max_length=20),
        ),
    ]
