# Generated by Django 5.2.17 on 2026-08-27 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_interaccioncliente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='liga_carpeta_adjuntos',
        ),
        migrations.AddField(
            model_name='lead',
            name='archivos_adjuntos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='siguiente_accion_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_siguiente_accion', to=settings.AUTH_USER_MODEL),
        ),
    ]
