# Generated by Django 5.2.17 on 2026-08-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_lead_liga_carpeta_adjuntos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='origen',
            field=models.CharField(choices=[('referido', 'Referido / Recomendación'), ('web', 'Sitio Web / Landing Page'), ('redes', 'Redes Sociales (LinkedIn/IG/FB)'), ('evento', 'Evento / Exposición / Feria'), ('directo', 'Contacto Directo / Inbound'), ('email', 'Mailing / Campaña Email'), ('licitacion', 'Licitación / RFP'), ('otro', 'Otro')], default='web', max_length=30),
        ),
    ]
