# Generated by Django 6.0.7 on 2026-07-21 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraObra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('porcentaje_avance', models.PositiveSmallIntegerField()),
                ('incidencias', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='proyectos.proyecto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de obra',
                'verbose_name_plural': 'Bitácoras de obra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=150)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(default='pza', max_length=20)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='obra.bitacoraobra')),
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='proyectos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='bitacoraobra',
            name='cuadrilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='obra.cuadrilla'),
        ),
        migrations.CreateModel(
            name='FotoAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='obra/avances/%Y/%m/')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='obra.bitacoraobra')),
            ],
        ),
    ]
