# Generated by Django 5.2.17 on 2026-08-19 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_options_alter_rol_options_and_more'),
        ('obra', '0001_initial'),
        ('proyectos', '0002_alter_fase_id_participacionempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumomaterial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fotoavance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='InventarioMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=150, unique=True)),
                ('unidad', models.CharField(default='pza', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=10.0, max_digits=12)),
                ('precio_unitario_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_materiales', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Inventario de Material',
                'verbose_name_plural': 'Inventario de Materiales',
                'ordering': ['material'],
            },
        ),
        migrations.CreateModel(
            name='OrdenIntercompania',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=255)),
                ('monto_interno', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estatus', models.CharField(choices=[('solicitada', 'Solicitada'), ('en_proceso', 'En Proceso'), ('entregada', 'Entregada'), ('liquidada', 'Liquidada')], db_index=True, default='solicitada', max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField()),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_entrantes', to='core.empresa')),
                ('empresa_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_salientes', to='core.empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_intercompania', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Orden Intercompañía',
                'verbose_name_plural': 'Órdenes Intercompañía',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='EstimacionObra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_estimacion', models.PositiveIntegerField()),
                ('fecha_presentacion', models.DateField()),
                ('porcentaje_ejecutado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('presentada', 'Presentada a Supervisión'), ('aprobada', 'Aprobada por Cliente'), ('facturada', 'Facturada')], db_index=True, default='borrador', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimaciones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Estimación de Obra',
                'verbose_name_plural': 'Estimaciones de Obra',
                'ordering': ['-numero_estimacion'],
                'unique_together': {('proyecto', 'numero_estimacion')},
            },
        ),
    ]
