# Generated by Django 6.0.7 on 2026-07-21 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquitectura', '0002_initial'),
        ('core', '0001_initial'),
        ('produccion', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('folio_fiscal', models.CharField(blank=True, help_text='UUID del CFDI, si aplica', max_length=60)),
                ('pagada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='core.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=14)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_cobrar', to='financiero.factura')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('modulo_origen', models.CharField(choices=[('arquitectura', 'Arquitectura'), ('proyecto', 'Proyecto / Obra'), ('produccion', 'Producción'), ('otro', 'Otro')], max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_detalle', to='core.empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='financiero.factura')),
                ('pedido_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produccion.pedido')),
                ('propuesta_diseno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arquitectura.propuestadiseno')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='proyectos.proyecto')),
            ],
        ),
    ]
