# Generated by Django 5.2.17 on 2026-08-19 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_options_alter_rol_options_and_more'),
        ('financiero', '0001_initial'),
        ('proyectos', '0002_alter_fase_id_participacionempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='pagada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor_nombre', models.CharField(max_length=200)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('pagada', models.BooleanField(db_index=True, default=False)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedor', to='core.empresa')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_proveedor', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Factura de Proveedor / CxP',
                'verbose_name_plural': 'Facturas de Proveedores / CxP',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
