# Generated by Django 6.0.7 on 2026-07-21 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_objeto', models.CharField(help_text='Ej. mesa, silla, clóset a medida', max_length=150)),
                ('especificaciones', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField()),
                ('estatus', models.CharField(choices=[('diseno', 'Diseño'), ('taller', 'En taller'), ('entrega', 'Listo para entrega'), ('entregado', 'Entregado')], default='diseno', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_produccion', to='core.cliente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_produccion', to='proyectos.proyecto')),
                ('responsable_taller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
