# Generated by Django 5.2.17 on 2026-08-19 22:57

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['capa', 'nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
                ('objects', apps.core.models.TodosManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='empresa',
            managers=[
                ('objects', apps.core.models.TodosManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.core.models.TodosManager()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='capa',
            field=models.CharField(choices=[('operativo', 'Operativo (Captura)'), ('jefe_area', 'Jefe de Área'), ('direccion', 'Dirección General')], default='operativo', help_text='Capa de acceso según el documento conceptual', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresas_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DocumentoAutorizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('plano', 'Plano / Diseño Arquitectónico'), ('orden_compra', 'Orden de Compra / CxP'), ('estimacion', 'Estimación de Obra'), ('cotizacion', 'Cotización Comercial'), ('contrato', 'Contrato / Convenio Legal'), ('otro', 'Solicitud Operativa')], default='plano', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('proyecto_nombre', models.CharField(blank=True, max_length=200)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente de Lectura'), ('visto', 'Visto (Acuse Registrado)'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_cambios', 'Requiere Cambios (Retrabajo)')], db_index=True, default='pendiente', max_length=25)),
                ('archivo_url', models.CharField(blank=True, max_length=500)),
                ('notas', models.TextField(blank=True)),
                ('visto_en', models.DateTimeField(blank=True, null=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('sla_horas', models.PositiveIntegerField(default=24)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('responsable_aprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_pendientes', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_autorizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('visto', 'Acuse de Recibo (Visto)'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_cambios', 'Requiere Cambios / Retrabajo'), ('comentado', 'Comentado'), ('modificado', 'Modificado')], db_index=True, max_length=30)),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('objeto_id', models.CharField(db_index=True, max_length=100)),
                ('objeto_repr', models.CharField(max_length=255)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('contrato_cliente', 'Contrato Marco con Cliente'), ('contrato_subcontrata', 'Contrato Subcontratista / Proveedor'), ('licencia_permiso', 'Licencia de Construcción / Permiso'), ('fianza_garantia', 'Fianza / Póliza de Garantía'), ('litigio_acta', 'Acta Notarial / Asunto Jurídico')], default='contrato_cliente', max_length=30)),
                ('monto_contrato', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('estatus', models.CharField(choices=[('en_revision', 'En Revisión Jurídica'), ('firmado', 'Firmado / Vigente'), ('por_vencer', 'Próximo a Vencer / Renovación'), ('concluido', 'Finiquitado / Concluido')], db_index=True, default='en_revision', max_length=20)),
                ('abogado_responsable', models.CharField(blank=True, max_length=150)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('clausulas_clave', models.TextField(blank=True)),
                ('archivo_url', models.CharField(blank=True, max_length=500)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_legales', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_legales', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha_firma'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('proveedor_nombre', models.CharField(max_length=200)),
                ('proyecto_nombre', models.CharField(blank=True, max_length=200)),
                ('concepto', models.CharField(max_length=255)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estatus', models.CharField(choices=[('solicitada', 'Solicitada / Requisición'), ('aprobada', 'Aprobada por Compras'), ('ordenada', 'Ordenada a Proveedor'), ('recibida', 'Insumos Recibidos en Almacén'), ('cancelada', 'Cancelada')], db_index=True, default='solicitada', max_length=20)),
                ('fecha_requisicion', models.DateField(auto_now_add=True)),
                ('fecha_entrega_esperada', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='core.empresa')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_requisicion'],
            },
        ),
        migrations.CreateModel(
            name='TicketPosventa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('proyecto_nombre', models.CharField(blank=True, max_length=200)),
                ('tipo_falla', models.CharField(choices=[('acabados', 'Detalle de Acabados / Pintura'), ('carpinteria', 'Desajuste de Carpintería / Muebles'), ('impermeabilizacion', 'Filtración / Muro Húmedo'), ('instalaciones', 'Instalación Eléctrica / Hidráulica'), ('otro', 'Atención General')], default='acabados', max_length=30)),
                ('descripcion_falla', models.TextField()),
                ('costo_reparacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estatus', models.CharField(choices=[('abierto', 'Reporte Abierto'), ('en_atencion', 'Técnico Asignado en Sitio'), ('resuelto', 'Reparación Concluida'), ('firmado_cliente', 'Finiquito de Garantía Firmado')], db_index=True, default='abierto', max_length=20)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('fecha_solucion_estimada', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_posventa', to='core.cliente')),
                ('empresa_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_posventa', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
