# Generated by Django 5.2.17 on 2026-08-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='especificaciones_brief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_deseada_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nivel_urgencia',
            field=models.CharField(choices=[('alta', 'Alta (Inmediata)'), ('media', 'Media (1 - 3 Meses)'), ('baja', 'Baja (Planeación)')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='presupuesto_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cliente',
            name='superficie_m2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_propiedad',
            field=models.CharField(choices=[('residencial', 'Residencial / Habitación'), ('comercial', 'Comercial / Retail'), ('industrial', 'Industrial / Nave'), ('corporativo', 'Corporativo / Oficinas'), ('hotelero', 'Turístico / Hotelero')], default='residencial', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
