# Generated by Django 5.2.17 on 2026-08-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_especificaciones_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad_municipio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_republica',
            field=models.CharField(default='CDMX', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
