# Generated by Django 5.2.17 on 2026-08-21 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_ciudad_municipio_cliente_estado_republica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('comercial', 'Ventas & CRM'), ('arquitectura', 'Arquitectura & Diseño'), ('obra', 'Obra & Operaciones'), ('produccion', 'Producción & Taller'), ('financiero', 'Finanzas & Tesorería'), ('compras', 'Compras & Procurement'), ('legal', 'Legal & Contratos'), ('rrhh', 'Recursos Humanos'), ('direccion', 'Dirección General')], default='comercial', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulos_permitidos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de claves de módulos visibles'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='monto_autorizacion_max',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Límite en $ MXN para firmas', max_digits=14),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reporta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL),
        ),
    ]
