# Generated by Django 5.2.17 on 2026-08-21 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_departamento_usuario_modulos_permitidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cliente_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_portal', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='capa',
            field=models.CharField(choices=[('direccion', 'Nivel 1: Dirección General (C-Suite)'), ('jefe_area', 'Nivel 2: Director / Gerente de Área'), ('coordinador', 'Nivel 3: Coordinador / Residente de Obra'), ('operativo', 'Nivel 4: Ejecutivo Operativo (Captura)'), ('cliente_external', 'Nivel 5: Portal del Cliente (Vista Exclusiva)')], default='operativo', help_text='Capa de acceso de seguridad', max_length=25),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('comercial', 'Ventas & CRM'), ('arquitectura', 'Arquitectura & 3D'), ('obra', 'Obra & Operaciones'), ('produccion', 'Producción & Taller'), ('financiero', 'Finanzas & Tesorería'), ('compras', 'Compras & Procurement'), ('legal', 'Legal & Licencias'), ('rrhh', 'Recursos Humanos'), ('direccion', 'Dirección General'), ('cliente', 'Portal de Cliente')], default='comercial', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulos_permitidos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='monto_autorizacion_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
